"""Safe local upload orchestration."""

import os
from pathlib import Path

from fastapi import UploadFile
from sqlalchemy.orm import Session

from app.core.config import Settings
from app.core.exceptions import (
    FeatureNotImplementedException,
    FileProcessException,
    PayloadTooLargeException,
    ResourceNotFoundException,
    UnsupportedFileTypeException,
    ValidationException,
)
from app.core.logger import get_logger
from app.models.file_record import FileRecord, FileStatus
from app.repositories.file_repository import FileRepository
from app.repositories.knowledge_base_repository import KnowledgeBaseRepository
from app.services.hash_service import HashService
from app.utils.file_utils import (
    ensure_directory,
    sanitize_filename,
    validate_file_extension,
)
from app.utils.id_utils import generate_file_id


logger = get_logger(__name__)


class FileService:
    """Validate and atomically persist uploads and their metadata."""

    COPY_CHUNK_SIZE = 1024 * 1024

    def __init__(self, db: Session, settings: Settings) -> None:
        self.db = db
        self.settings = settings
        self.file_repository = FileRepository(db)
        self.knowledge_base_repository = KnowledgeBaseRepository(db)

    def upload_file(
        self,
        knowledge_base_id: str,
        upload_file: UploadFile,
    ) -> FileRecord:
        """Store one upload and commit a ``PENDING`` metadata record.

        The temporary and final paths are generated by this service.  On any
        pre-commit failure, only those exact paths are eligible for cleanup.
        """
        temp_path: Path | None = None
        final_path: Path | None = None
        temp_created = False
        final_created = False
        committed = False

        try:
            if self.knowledge_base_repository.get_by_id(knowledge_base_id) is None:
                raise ResourceNotFoundException("知识库不存在")

            try:
                original_name = sanitize_filename(upload_file.filename or "")
            except ValueError as exc:
                raise ValidationException(str(exc)) from exc

            try:
                extension = validate_file_extension(
                    original_name,
                    self.settings.ALLOWED_FILE_EXTENSIONS,
                )
            except ValueError as exc:
                raise UnsupportedFileTypeException(str(exc)) from exc

            upload_directory = ensure_directory(self.settings.UPLOAD_DIR)
            file_id = generate_file_id()
            stored_name = f"{file_id}{extension}"
            temp_path = upload_directory / f".{file_id}.uploading"
            final_path = upload_directory / stored_name
            if temp_path.exists() or final_path.exists():
                raise FileProcessException("生成的存储文件名发生冲突")

            file_size = self._write_bounded_temp_file(upload_file, temp_path)
            temp_created = True
            content_md5 = HashService.calculate_file_md5(temp_path)
            os.replace(temp_path, final_path)
            temp_created = False
            final_created = True

            record = self.file_repository.create(
                id=file_id,
                knowledge_base_id=knowledge_base_id,
                original_name=original_name,
                stored_name=stored_name,
                file_path=final_path.resolve()
                .relative_to(self.settings.DATA_DIR.resolve())
                .as_posix(),
                file_type=extension,
                file_size=file_size,
                md5=content_md5,
                status=FileStatus.PENDING,
                chunk_count=0,
                error_message=None,
            )
            self.db.commit()
            committed = True
            return record
        except Exception:
            if not committed:
                try:
                    self.db.rollback()
                finally:
                    if temp_created:
                        self._cleanup_file(temp_path)
                    if final_created:
                        self._cleanup_file(final_path)
            raise

    def _write_bounded_temp_file(
        self,
        upload_file: UploadFile,
        temp_path: Path,
    ) -> int:
        """Copy an upload in chunks and enforce its actual byte size."""
        max_bytes = self.settings.MAX_UPLOAD_SIZE_MB * 1024 * 1024
        bytes_written = 0
        temp_created = False
        try:
            upload_file.file.seek(0)
            with temp_path.open("xb") as destination:
                temp_created = True
                while chunk := upload_file.file.read(self.COPY_CHUNK_SIZE):
                    bytes_written += len(chunk)
                    if bytes_written > max_bytes:
                        raise PayloadTooLargeException(
                            f"文件大小不能超过 {self.settings.MAX_UPLOAD_SIZE_MB} MiB"
                        )
                    destination.write(chunk)
                destination.flush()
                os.fsync(destination.fileno())
        except PayloadTooLargeException:
            if temp_created:
                self._cleanup_file(temp_path)
            raise
        except OSError as exc:
            if temp_created:
                self._cleanup_file(temp_path)
            raise FileProcessException("保存上传文件失败") from exc
        except Exception as exc:
            if temp_created:
                self._cleanup_file(temp_path)
            raise FileProcessException("读取上传文件失败") from exc

        if bytes_written == 0:
            self._cleanup_file(temp_path)
            raise ValidationException("上传文件不能为空")
        return bytes_written

    @staticmethod
    def _cleanup_file(file_path: Path | None) -> None:
        """Remove one exact temporary/upload path if this attempt created it."""
        if file_path is None:
            return
        try:
            file_path.unlink(missing_ok=True)
        except OSError:
            logger.exception("无法清理上传失败后残留的文件：%s", file_path)

    def list_files(self, knowledge_base_id: str) -> list[FileRecord]:
        _ = knowledge_base_id
        raise FeatureNotImplementedException("文件列表功能尚未完成初始化")

    def get_file(self, file_id: str) -> FileRecord:
        _ = file_id
        raise FeatureNotImplementedException("文件查询功能尚未完成初始化")

    def delete_file(self, file_id: str) -> FileRecord:
        _ = file_id
        raise FeatureNotImplementedException("文件删除功能尚未完成初始化")
